---
- name: PowerDNS backed by MariaDB install
  hosts: all
  become: yes
  tasks:
    - name: Include credentials file
      include_vars: "{{ playbook_dir }}/../data/credentials/credentials.yml"

    - name: Execute MariaDB tasks
      include_role:
        name: geerlingguy.mysql

    - name: Copy schema file to master
      copy:
        src: "{{ playbook_dir }}/../data/pdns/schema.mysql.sql"
        dest: schema.mysql.sql
        force: yes
      when: "'master' in group_names"

    - name: Execute pdns SQL schema
      mysql_db: 
        name: pdns
        state: import
        target: schema.mysql.sql
      when: "'master' in group_names"
    
    - name: Execute PDNS tasks
      include_role:
        name: powerdns.pdns
      vars:
        # Not ready as a default in pdns 1.7.0 plugin yet
        pdns_install_repo:
          apt_repo_origin: "repo.powerdns.com"
          apt_repo: "deb [arch=amd64] http://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-auth-45 main"
          gpg_key: "http://repo.powerdns.com/FD380FBB-pub.asc"
          gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
          yum_repo_baseurl: "http://repo.powerdns.com/centos/$basearch/$releasever/auth-45"
          yum_debug_symbols_repo_baseurl: "http://repo.powerdns.com/centos/$basearch/$releasever/auth-45/debug"
          name: "powerdns-auth-45"
    
    - name: Execute PDNS recursor setup tasks
      include_role:
        name: powerdns.pdns_recursor
      vars:
        # Not ready as a default in pdns_recursor 1.5.0 plugin yet
        pdns_rec_install_repo:
          apt_repo_origin: "repo.powerdns.com"
          apt_repo: "deb [arch=amd64] http://repo.powerdns.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }}-rec-46 main"
          gpg_key: "http://repo.powerdns.com/FD380FBB-pub.asc"
          gpg_key_id: "9FAAA5577E8FCF62093D036C1B0C6205FD380FBB"
          yum_repo_baseurl: "http://repo.powerdns.com/centos/$basearch/$releasever/auth-46"
          yum_debug_symbols_repo_baseurl: "http://repo.powerdns.com/centos/$basearch/$releasever/rec-46/debug"
          name: "powerdns-rec-46"